all_domain = [
    "attraction-type",
    "attraction-name",
    "attraction-area",
    
    "hotel-pricerange",
    "hotel-type",
    "hotel-parking",
    "hotel-day", 
    "hotel-stars",
    "hotel-internet",
    "hotel-name",
    "hotel-people",
    "hotel-area",
    "hotel-stay",

    "restaurant-time",
    "restaurant-pricerange",
    "restaurant-day",
    "restaurant-area",
    "restaurant-food",
    "restaurant-name",
    "restaurant-people",

    "train-destination",
    "train-departure",
    "train-arrive",
    "train-day",
    "train-people",
    "train-leave",

    "taxi-leave",
    "taxi-destination",
    "taxi-arrive",
    "taxi-departure",
]